// The learner's second chance.
//
// A model cannot count characters, so "keep the whole file under N chars" is
// the least reliable instruction in the main prompt — and for a long time
// missing it threw away the entire day's learning. These build the follow-up
// ask: the model's own rejected draft, plus exactly what was wrong with it.
//
// Only ever used for SOFT violations (see guardrail-severity.mjs). Hard ones
// stop the run dead.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GUARDRAILS = JSON.parse(fs.readFileSync(path.join(__dirname, 'guardrails.json'), 'utf8'));

// Turn one soft violation into an instruction the model can actually act on.
// "Too long" is useless; "you are 82 over, cut 582" is a task.
export function retryInstruction(problem, rejected) {
  const { limits } = GUARDRAILS;
  switch (problem.rule) {
    case 'size/max': {
      // Aim well under the ceiling — a model that trims to exactly the limit
      // lands over it about as often as not.
      const target = limits.maxChars - 500;
      return `- TOO LONG. Your draft is ${rejected.length} characters; the hard limit is ${limits.maxChars}. Cut at least ${rejected.length - target} characters to land near ${target}. Cut ONLY by deleting whole lines — pick the weakest, most generic or redundant bullets and remove them entirely. Prefer deleting lines that are NOT in the live file below (your own additions and rephrasings). NEVER reword, merge, or compress the lines you keep: a separate check rejects the file unless enough lines of the live file survive character-for-character. Do not add anything.`;
    }
    case 'size/min':
      return `- TOO SHORT. Your draft is only ${rejected.length} characters (minimum ${limits.minChars}) — it looks truncated. Return the complete file, every section filled in.`;
    case 'structure/sections':
      return `- TOO MANY SECTIONS. ${problem.detail} Consolidate related sections; do not simply delete one.`;
    case 'structure/header':
    case 'structure/marker':
      return `- WRONG SHAPE. ${problem.detail} Keep the content, fix the structure.`;
    case 'churn/growth':
      return `- GREW TOO FAST. ${problem.detail} Keep only the strongest of what you added and leave the rest of the file alone.`;
    case 'churn/deletion':
    case 'churn/rewrite':
      return `- TOO MUCH WAS LOST. ${problem.detail} Start again from the current file below and change as little as possible.`;
    case 'empty':
      return `- EMPTY OUTPUT. You returned nothing. Return the complete file.`;
    default:
      return `- ${problem.detail}`;
  }
}

// Second (and third) pass: hand the model its own rejected draft plus the
// specific complaint. Deliberately does NOT include the transcripts again —
// this is a reshaping task, not another round of learning, and leaving them out
// keeps the model from "fixing" the length by inventing new material.
export function buildRetryPrompt(currentLearnings, rejected, softProblems) {
  return `The draft you just produced for \`knowledge/learnings.md\` was rejected by the automated
validator. Nothing unsafe was in it — it is the wrong size or the wrong shape. Fix exactly
what is listed below and change nothing else.

# What the validator objected to
${softProblems.map((p) => retryInstruction(p, rejected)).join('\n')}

# Your rejected draft
<rejected_draft>
${rejected}
</rejected_draft>

# The file currently live, which the draft is replacing
<current_learnings>
${currentLearnings}
</current_learnings>

# Facts that are settled and may never be contradicted
${GUARDRAILS.immutableFacts.map((f) => `- ${f}`).join('\n')}

# Rules that still apply
- You are trimming and reshaping the draft, not learning again. Do not introduce a single new observation.
- When cutting for length, delete whole lines; never reword a line that also appears in the live file — kept lines must stay character-for-character identical.
- Never write a client name, phone number, email, price, area or availability status.
- Never write a percentage other than the settled ones above. Never write "8%".
- Same terse, imperative style. No preamble, no commentary, no explanation of what you changed.

# Output format
Return ONLY the complete corrected file, starting with the line:
${GUARDRAILS.requiredHeader}

It must contain these sections, in this order:
${GUARDRAILS.requiredMarkers.filter((m) => m.startsWith('##')).join('\n')}
## Language & audience
## Gaps a human must answer

Immediately after the H1 line, include the marker comment:
<!-- AUTO-GENERATED by scripts/learn-from-chats.mjs — human edits are fine, they get merged not overwritten. Last run: ${new Date().toISOString().slice(0, 10)} -->

After the file content, on a new line, output exactly:
DIGEST: <one sentence, max 25 words, on what changed and why>`;
}
